import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import SideBar from "@/app/_components/side-bar";
import Header from "@/app/_components/header";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      <body className={nunitoSans.className}>
        <div className="flex relative">
          <SideBar/>
          <div className="bg-body w-screen">
            <Header/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
