import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import SideBar from "@/app/_components/side-bar";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} >
      <body className={nunitoSans.className}>
        <div className="flex relative">
          <SideBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
